[project]
name = "akiro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.4",
    "sqlalchemy>=2.0.36",
    "uvicorn>=0.32.0",
]
